import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AdSense from "./components/Adsene";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* pass only the numeric publisher id (no "ca-pub-" prefix) */}
        <AdSense pId="9822891837132664" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}